### ISSUE TITLE
hex() block

### ISSUE THREAD

**Issue by sk8board** [QuirkyCort/IoTy#8]
IoTy is a nice tool for ESP32. I was using the I2C scan block and noticed there is not a block for converting the result to hex.

Could you add a hex() block for converting the result of an I2C scan to hexadecimal?

**Comment by QuirkyCort** [comment]
I've added it to the "convert to" block under "Data". You can now select "hexadecimal string" as a conversion target.

To convert hex string to int, you can just do a "convert to integer".

Do note that an i2c scan returns a list, so you'll need to iterate through when converting to hex.

**Comment by sk8board** [comment]
Thank you. It works great.

By the way, this has to be the quickest completion of a feature request on GitHub. :)
